{% set name = "azure-synapse-spark" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure-synapse-spark-{{ version }}.zip
  sha256: 86fa29463a24b7c37025ff21509b70e36b4dace28e5d92001bc920488350acd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - msrest >=0.5.0
    - azure-common >=1.1,<2.dev0
    - azure-core >=1.6.0,<2.0.0
    - azure-synapse-nspkg

test:
  imports:
    - azure.synapse.spark
    - azure.synapse.spark.aio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Synapse Spark Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
